### ISSUE TITLE
Possible Duplicate User Registration

### ISSUE THREAD

**Issue by chankiyu22** [Auto-Advisor/autoadvisor#16]
When I use autoadvisoraws@gmail.com to register, it is still possible to register again, and sent a confirmation letter. After that, without confirmation, the original account is not accessable.

**Comment by duane** [comment]
Is this a bug? It would be expected behavior for me. As long as you can't duplicate an a confirmed account, it shouldn't be an issue.

**Comment by chankiyu22** [comment]
I think it is better to set a timeout to prevent duplicate user registration in a short time. By the way, do we have a mechanism to clean up unconfirmed users?

**Comment by duane** [comment]
No, but I would hardly consider either of them priorities at this point or blocking other features. Anyone mind if I just clear the milestone on this? I will probably have time to address it after beta as the auth code isn't mine, it's another library.

**Comment by iswei** [comment]
solved in new layout, only unique email and username can register
