### ISSUE TITLE
no protection in uploading transcripts or individual courses

### ISSUE THREAD

**Issue by nconlon** [Auto-Advisor/autoadvisor#37]
-There are no checks (file type, file seize, ect....) for uploading a transcript
-There are no checks to make sure users upload correct individual courses

**Comment by duane** [comment]
If courses are not in the database, they are added with a flag to mark them as "hidden", when uploading a transcript. Individual credit adds fail when they cannot be looked up in the database. I am unsure whether the security aspect

**Comment by nconlon** [comment]
this was from before credit adds failed.
