### ISSUE TITLE
rake db:setup fails

### ISSUE THREAD

**Issue by dwemhoen** [Auto-Advisor/autoadvisor#56]
When I try to run the command
rake db:setup
I get the following error:

Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "database"=>"autoadvisor_dev", "username"=>"root", "password"=>"password", "host"=>"localhost", "port"=>3306, "pool"=>5, "timeout"=>5000}, charset: utf8, collation: 
(if you set the charset manually, make sure you have a matching collation)
Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "database"=>"autoadvisor_test", "username"=>"root", "password"=>"password", "host"=>"localhost", "port"=>3306, "pool"=>5, "timeout"=>5000}, charset: utf8, collation: 
(if you set the charset manually, make sure you have a matching collation)
rake aborted!
Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
/var/lib/gems/1.9.1/gems/mysql2-0.3.11/lib/mysql2/client.rb:44:in `connect'
/var/lib/gems/1.9.1/gems/mysql2-0.3.11/lib/mysql2/client.rb:44:in`initialize'
/var/lib/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/mysql2_adapter.rb:16:in `new'
/var/lib/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/mysql2_adapter.rb:16:in`mysql2_connection'
/var/lib/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:315:in `new_connection'
/var/lib/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:325:in`checkout_new_connection'
/var/lib/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:247:in `block (2 levels) in checkout'
/var/lib/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in`loop'
/var/lib/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `block in checkout'
/var/lib/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:239:in`checkout'
/var/lib/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:102:in `block in connection'
/var/lib/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:101:in`connection'
/var/lib/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:410:in `retrieve_connection'
/var/lib/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_specification.rb:171:in`retrieve_connection'
/var/lib/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_specification.rb:145:in `connection'
/var/lib/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/model_schema.rb:308:in`clear_cache!'
/var/lib/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/railtie.rb:97:in `block (2 levels) in <class:Railtie>'
/var/lib/gems/1.9.1/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:418:in`_run__2901861535014535750__prepare__1940998041071204235__callbacks'
/var/lib/gems/1.9.1/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:405:in `__run_callback'
/var/lib/gems/1.9.1/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:385:in`_run_prepare_callbacks'
/var/lib/gems/1.9.1/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/lib/gems/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/reloader.rb:74:in`prepare!'
/var/lib/gems/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/reloader.rb:48:in `prepare!'
/var/lib/gems/1.9.1/gems/railties-3.2.12/lib/rails/application/finisher.rb:47:in`block in module:Finisher'
/var/lib/gems/1.9.1/gems/railties-3.2.12/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/1.9.1/gems/railties-3.2.12/lib/rails/initializable.rb:30:in`run'
/var/lib/gems/1.9.1/gems/railties-3.2.12/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/lib/gems/1.9.1/gems/railties-3.2.12/lib/rails/initializable.rb:54:in`each'
/var/lib/gems/1.9.1/gems/railties-3.2.12/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/1.9.1/gems/railties-3.2.12/lib/rails/application.rb:136:in`initialize!'
/var/lib/gems/1.9.1/gems/railties-3.2.12/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/david/autoadvisor/config/environment.rb:5:in`<top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gems/1.9.1/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in`block in require'
/var/lib/gems/1.9.1/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in `load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in`require'
/var/lib/gems/1.9.1/gems/railties-3.2.12/lib/rails/application.rb:103:in `require_environment!'
/var/lib/gems/1.9.1/gems/railties-3.2.12/lib/rails/application.rb:297:in`block (2 levels) in initialize_tasks'
Tasks: TOP => db:setup => db:schema:load_if_ruby => environment
(See full trace by running task with --trace)

I tried to check my.cnf, however it isn't located in the location the wiki indicates. For my setup it is in etc/mysql/my.cnf. When I open this there is no line for host or password. Should I just add these lines? If so, where? The config file looks like:
# 
# The MySQL database server configuration file.
# 
# You can copy this to one of:
# \- "/etc/mysql/my.cnf" to set global options,
# \- "~/.my.cnf" to set user-specific options.
# 
# One can use all long options that the program supports.
# Run program with --help to get a list of available options and with
# --print-defaults to see which it would actually understand and use.
# 
# For explanations see
# http://dev.mysql.com/doc/mysql/en/server-system-variables.html
# This will be passed to all mysql clients
# It has been reported that passwords should be enclosed with ticks/quotes
# escpecially if they contain "#" chars...
# Remember to edit /etc/mysql/debian.cnf when changing the socket location.

[client]
port        = 3306
socket      = /var/run/mysqld/mysqld.sock
# Here is entries for some specific programs
# The following values assume you have at least 32M ram
# This was formally known as [safe_mysqld]. Both versions are currently parsed.

[mysqld_safe]
socket      = /var/run/mysqld/mysqld.sock
nice        = 0

[mysqld]
# 
# \* Basic Settings
# 

user        = mysql
pid-file    = /var/run/mysqld/mysqld.pid
socket      = /var/run/mysqld/mysqld.sock
port        = 3306
basedir     = /usr
datadir     = /var/lib/mysql
tmpdir      = /tmp
lc-messages-dir = /usr/share/mysql
skip-external-locking
# 
# Instead of skip-networking the default is now to listen only on
# localhost which is more compatible and is not less secure.

bind-address        = 127.0.0.1
# 
# \* Fine Tuning
# 

key_buffer      = 16M
max_allowed_packet  = 16M
thread_stack        = 192K
thread_cache_size       = 8
# This replaces the startup script and checks MyISAM tables if needed
# the first time they are touched

myisam-recover         = BACKUP
# max_connections        = 100
# table_cache            = 64
# thread_concurrency     = 10
# 
# \* Query Cache Configuration
# 

query_cache_limit   = 1M
query_cache_size        = 16M
# 
# \* Logging and Replication
# 
# Both location gets rotated by the cronjob.
# Be aware that this log type is a performance killer.
# As of 5.1 you can enable the log at runtime!
# general_log_file        = /var/log/mysql/mysql.log
# general_log             = 1
# 
# Error log - should be very few entries.
# 

log_error = /var/log/mysql/error.log
# 
# Here you can see queries with especially long duration
# log_slow_queries   = /var/log/mysql/mysql-slow.log
# long_query_time = 2
# log-queries-not-using-indexes
# 
# The following can be used as easy to replay backup logs or for replication.
# note: if you are setting up a replication slave, see README.Debian about
# other settings you may need to change.
# server-id      = 1
# log_bin            = /var/log/mysql/mysql-bin.log

expire_logs_days    = 10
max_binlog_size         = 100M
# binlog_do_db       = include_database_name
# binlog_ignore_db   = include_database_name
# 
# \* InnoDB
# 
# InnoDB is enabled by default with a 10MB datafile in /var/lib/mysql/.
# Read the manual for more InnoDB related options. There are many!
# 
# \* Security Features
# 
# Read the manual, too, if you want chroot!
# chroot = /var/lib/mysql/
# 
# For generating SSL certificates I recommend the OpenSSL GUI "tinyca".
# 
# ssl-ca=/etc/mysql/cacert.pem
# ssl-cert=/etc/mysql/server-cert.pem
# ssl-key=/etc/mysql/server-key.pem

[mysqldump]
quick
quote-names
max_allowed_packet  = 16M

[mysql]
# no-auto-rehash # faster start of mysql but no tab completition

[isamchk]
key_buffer      = 16M
# 
# \* IMPORTANT: Additional settings that can override those from this file!
# The files must end with '.cnf', otherwise they'll be ignored.
# 

!includedir /etc/mysql/conf.d/

**Comment by duane** [comment]
Pretty sure you need to set your password, or something equally silly. if `mysql -uroot -ppassword` fails with something like: `ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)`, then follow instructions outlined [here](https://gist.github.com/duane/5332758). Otherwise, hop on IRC and we can sort it out.

**Comment by duane** [comment]
Confirmed this does not happen with a correct MySQL setup. See me for help setting MySQL up.
