### ISSUE TITLE
GPA calculation

### ISSUE THREAD

**Issue by godinj** [Auto-Advisor/autoadvisor#63]
You guys did not list this as a functional feature for the Beta release.
However, we wanted to be sure that you are aware of these issues:
- Adding a transcript item allows a grade over 4.0 and under 0.0 (negative), and computes the overall GPA in an unintuitive way when strange grades are inputted.
- Credits are not displayed anywhere, GPA is just an average (not weighted)
- After removing a transcript item, the GPA still remains. It’s overridden when the next transcript is uploaded, but it can still be confusing.

**Comment by nconlon** [comment]
GPA is now calculated correctly
