### ISSUE TITLE
Typo's and punctuation

### ISSUE THREAD

**Issue by godinj** [Auto-Advisor/autoadvisor#64]
- Extra period under "Cancel my account" on the Edit Account page.
- The asterisk next to "UPLOAD TRANSCRIPT" on the transcript page seems to imply it's a required field but is in fact a footnote. This is confusing.
- The “d” in the “Recommend” button is cut off.
- Perhaps change “All class” to “All classes”
- Upload transcript page has a typo: “Please only upload Unofficial UMass transcirpts”

**Comment by nconlon** [comment]
typo's fixed, footnote and '*' removed.
