### ISSUE TITLE
Cosmetic/Aesthetic suggestions

### ISSUE THREAD

**Issue by godinj** [Auto-Advisor/autoadvisor#65]
- Clicking in the search text bar on the Schedule page does not clear the default text as expected.
- Filter section needs cosmetic fixes for checkboxes and positioning on the page.
- Filter button seems to be a text field. Strange behavior (i.e. highlighting the text) when clicking on it.
- Course description needs formatting in Class Availability section, hard to read as is

**Comment by nconlon** [comment]
Updated the UI.
