### ISSUE TITLE
Class descriptions inconsistent

### ISSUE THREAD

**Issue by godinj** [Auto-Advisor/autoadvisor#66]
Again, although you listed Browse/Filter classes as a feature to be implemented for the final release, we thought it was worth mentioning.
- Details for default CS320 class are for CS326 (quoted below)
  Enrollemnt Requirement
  Open to Computer Science majors only. Prerequisite: CMPSCI 187 or E&C-ENG 242 with a grade of 'C' or better. CMPSCI MINORS, APPLICANTS-ON-CONTRACT, AND OTHERS NOT MEETING ELIGIBILITY, OR STUDENTS NEEDING SPECIAL PERMISSION MUST REQUEST OVERRIDES VIA THE ON-LINE FORM:https://www.cs.umass.edu/ugrad-education/courses . COURSE NUMBER CHANGED FROM 390WP TO 326.

**Comment by dstubbs** [comment]
The class descriptions in the database were placeholders, and will be wiped out in favor of better (pdf-parsing permitting) data before release.
