### ISSUE TITLE
Enable SSL for auth

### ISSUE THREAD

**Issue by duane** [Auto-Advisor/autoadvisor#7]
Auth currently happens in plaintext. DO NOT USE REAL PASSWORD.

**Comment by iswei** [comment]
is this an issue?  to enable ssl for authorization including securing cookies go to config/environments/production.rb and set  config.force_ssl = true, this will add the secure socket layer to the sign up and sign in functions.

**Comment by duane** [comment]
Not worth our time. Don't use a password you have in use other places; you should assume that someone found it and added it to a dictionary.
