### ISSUE TITLE
Lost password can't be recovered.

### ISSUE THREAD

**Issue by chenh918** [Auto-Advisor/autoadvisor#9]
After the initial sign up. Let's say you forgot the password. Then you click on the link under the login bars "Forgot your password?".  Then enter the registered email address. Once finished, click on the button below.  Shortly after, you should receive a email with a link to reset your password from AutoAdvisor, when you click on the link, you will realize that it is not a working link(dead link).

**Comment by duane** [comment]
Please reproduce by posting confirmation link.  I think that I may have fixed this bug as well when I fixed the last one; it wasn't a dead link, it was using the wrong port (which was my fault).
